name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # Enables manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://freeAAk48:$HF_TOKEN@huggingface.co/spaces/freeAAk48/HF_Model_Quantizer main -f
